// Auto-generated by MetricsDashboardCallback — do not edit
window.DASHBOARD_DATA = {
  "run_name": "lstm_v17_check seed=42",
  "generated_at": "2026-04-28T04:30:45Z",
  "elapsed_seconds": 28,
  "timestep": 2048,
  "total_timesteps": 100,
  "progress_pct": 2048.0,
  "n_episodes_sampled": 200,
  "rolling_window": 200,
  "avg_lifespan": 8.925,
  "avg_f_metric": null,
  "avg_strength": 0.45586792956182265,
  "avg_action_rates": {
    "walk_away": 0.0314,
    "move_w": 0.0856,
    "train": 0.6507,
    "eat": 0.2221,
    "attack": 0.2025,
    "move_e": 0.0749,
    "withdraw": 0.0128,
    "defend": 0.0473,
    "collaborate": 0.0269,
    "deposit": 0.0414,
    "rest": 0.0724,
    "move_s": 0.0761,
    "gather": 0.1773,
    "move_n": 0.0607
  },
  "avg_hazard_approaches": {
    "poison": 0.34,
    "mountain": 0.4,
    "flame": 0.45
  },
  "avg_hazard_flees": {
    "poison": 0.39,
    "mountain": 0.3,
    "flame": 0.39
  },
  "hazard_approach_ratio": {
    "poison": 0.465,
    "mountain": 0.568,
    "flame": 0.536
  },
  "avg_resistance_gained": {},
  "avg_agent_credit": [
    0.042,
    0.0883,
    0.0865,
    -0.5714,
    0.0721,
    -0.4379,
    -0.0026,
    0.0033,
    0.0015,
    0.0161
  ],
  "avg_power": 0.2659898562685635,
  "avg_final_power": 0.20733646585638316,
  "avg_deaths_by_age": 0.0,
  "avg_deaths_by_cause": {
    "starvation": 2.25
  },
  "avg_reproductions": 0.22,
  "avg_stash_fill_rate": 0.024744047619047624,
  "avg_stash_withdraw_rate": 0.0025,
  "avg_dist_from_stash": 0.11531701993658515,
  "avg_revisit_entropy": 1.192227385282526,
  "avg_group_persistence": 0.16,
  "history": [
    {
      "timestep": 2048,
      "f_metric": null,
      "avg_lifespan": 8.925
    }
  ]
};
