// Auto-generated by MetricsDashboardCallback — do not edit
window.DASHBOARD_DATA = {
  "run_name": "smoke_ippo_prep seed=0",
  "generated_at": "2026-04-29T21:35:24Z",
  "elapsed_seconds": 64,
  "timestep": 4096,
  "total_timesteps": 4096,
  "progress_pct": 100.0,
  "n_episodes_sampled": 76,
  "rolling_window": 200,
  "avg_lifespan": 52.68421052631579,
  "avg_f_metric": null,
  "avg_strength": 0.5150236419314151,
  "avg_action_rates": {
    "gather": 0.0868,
    "train": 0.5031,
    "collaborate": 0.0331,
    "rest": 0.0682,
    "move_n": 0.0634,
    "walk_away": 0.0293,
    "eat": 0.0357,
    "attack": 0.0261,
    "move_s": 0.0643,
    "move_w": 0.0717,
    "deposit": 0.0386,
    "move_e": 0.0599,
    "defend": 0.0256,
    "attack_burst": 0.0238,
    "attack_qi": 0.0233
  },
  "avg_hazard_approaches": {
    "mountain": 4.88,
    "poison": 5.13,
    "flame": 5.54
  },
  "avg_hazard_flees": {
    "mountain": 4.8,
    "poison": 4.93,
    "flame": 5.42
  },
  "hazard_approach_ratio": {
    "flame": 0.505,
    "mountain": 0.504,
    "poison": 0.51
  },
  "avg_resistance_gained": {},
  "avg_agent_credit": [
    0.0206,
    0.0737,
    0.0826,
    0.043,
    0.0279,
    0.0937,
    0.0766,
    0.0977,
    0.0682,
    0.0611
  ],
  "avg_power": 0.27715920511069203,
  "avg_final_power": 0.24463830885659651,
  "avg_deaths_by_age": 0.0,
  "avg_deaths_by_cause": {
    "starvation": 5.951612903225806
  },
  "avg_reproductions": 4.855263157894737,
  "avg_stash_fill_rate": 1.0524122807017544,
  "avg_stash_withdraw_rate": 0.0,
  "avg_dist_from_stash": 1.8156199302024796,
  "avg_revisit_entropy": 2.984465242707822,
  "avg_group_persistence": 31.098684210526315,
  "history": [
    {
      "timestep": 4096,
      "f_metric": null,
      "avg_lifespan": 52.68421052631579
    }
  ]
};
